post_install() {
  echo "A sample config is included at /usr/share/vkPost/vkPost.conf.example"
  echo "Please copy it over to ~/.config/vkPost/vkPost.conf to have vkPost use it"
}

post_upgrade() {
  echo "The config file example at /usr/share/vkPost/vkPost.conf.example may have been updated."
  echo "You may want to check it for anything new you would like to use, in your own user config file at ~/.{config,local/share}/vkPost/vkPost.conf ."
}
